version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./codeigniter.env:/var/www/evalform/.env
    ports:
      - 80:80
    environment:
      EVALFORM_ADMIN: ${EVALFORM_ADMIN}
      EVALFORM_ADMIN_PASSWORD: ${EVALFORM_ADMIN_PASSWORD}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db_data: